[package]
name = "bitvisor_process_lib"
version = "0.1.0"
authors = ["Masanori Misono <m.misono760@gmail.com>"]

[dependencies]
spin = "0.4.6"
rlibc = "1.0"
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
